#!/bin/bash

# https://stackoverflow.com/a/246128
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )"

chat -v -f $SCRIPT_DIR/modem-answer.script && pppd +ipv6
